# Generated by Django 4.2.6 on 2023-10-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
